### ISSUE TITLE
怎么启用屏幕亮度控制呢？

### ISSUE THREAD

**Issue by Hsiao-Jan** [s1973/hackintosh-hasee-k650d-i7-d3#1]
我看了一下你详细的教程去安装，用了你的clover，现在成功安装了，非常感谢，但是我没有看懂你写的如何启用屏幕亮度控制这个部分。我去搜索了一下，我尝试了几个方法：1、用clover Configurator直接对config.plist进行修改，在acpi设置里点击了添加PNLF，保存重启没有效果。2、我下载下来了你指定的修改版的whatevergreen包，将他的SSDT-PNLF.dsl另存为SSDT-PNLF.aml，然后放到ACPI/PATCHED目录下，可是用maciasl工具保存后自己又变成了原来的SSDT-PNLF.aml，爬贴我也没找到该怎样弄。请问你可以详细说一下吗？
以上环境是K650D-i7D3,自己加了一个msata的固态，使用你提供的这个clover，没做过修改

**Comment by s1973** [comment]
Clover方案需要 启用名为 `AddPNLF` 的 DSDT 补丁与 `SetIntelBacklight`, `SetIntelMaxBacklight` 两项

> *clover*修复和*SSDT*二选其一，不要同时使用；同时注意移除其他亮度补丁和驱动

[官方文档](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.cn.md#%E8%B0%83%E8%8A%82%E7%AC%94%E8%AE%B0%E6%9C%AC%E4%BA%AE%E5%BA%A6)中已经添加了[SSDT-PNLF.aml](https://i.applelife.ru/2019/05/450784_SSDT-PNLF.aml.zip)下载

**Comment by Hsiao-Jan** [comment]
我想用SSDT打补丁的，我下载下来你指定的那个SSDT以后，这个文件应该是11KB的，不知道为什么移动到patched里面又自己变成原来的样子了……我晚上再移动一下看看，正确操作是不是下载下来以后放在clover的patched里就行？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ssssss <notifications@github.com&gt;
发送时间: 2019年11月29日 09:31
收件人: s1973/hackintosh-hasee-k650d-i7-d3 <hackintosh-hasee-k650d-i7-d3@noreply.github.com&gt;
抄送: Hsiao_Jan <1065368543@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[s1973/hackintosh-hasee-k650d-i7-d3] 怎么启用屏幕亮度控制呢？ (#1)




clover修复和SSDT二选其一，不要同时使用；同时注意移除其他补丁和驱动
 
官方文档里添加了SSDT-PNLF.aml下载

**Comment by s1973** [comment]
*SSDT-PNLF.aml* 放到 `/CLOVER/ACPI/patched/`目录下，去我上面贴的地址下载

**Comment by Hsiao-Jan** [comment]
嗯嗯，我之前就是用的你贴地址的这个啦，我晚上回家再试试，非常感谢你的教程！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ssssss <notifications@github.com&gt;
发送时间: 2019年11月29日 09:46
收件人: s1973/hackintosh-hasee-k650d-i7-d3 <hackintosh-hasee-k650d-i7-d3@noreply.github.com&gt;
抄送: Hsiao_Jan <1065368543@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[s1973/hackintosh-hasee-k650d-i7-d3] 怎么启用屏幕亮度控制呢？ (#1)




SSDT-PNLF.aml 放到 /CLOVER/ACPI/patched/目录下，去我上面贴的地址下载

**Comment by s1973** [comment]
那个地址好像打不开，我这个库里有直接编译好的[*SSDT-PNLF.aml*](https://github.com/s1973/hackintosh-hasee-k650d-i7-d3/blob/master/CLOVER/ACPI/patched/SSDT-PNLF.aml)，[下载](https://github.com/s1973/hackintosh-hasee-k650d-i7-d3/raw/master/CLOVER/ACPI/patched/SSDT-PNLF.aml)下来即可

**Comment by Hsiao-Jan** [comment]
好的好的，多谢你啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ssssss <notifications@github.com&gt;
发送时间: 2019年11月29日 09:53
收件人: s1973/hackintosh-hasee-k650d-i7-d3 <hackintosh-hasee-k650d-i7-d3@noreply.github.com&gt;
抄送: Hsiao_Jan <1065368543@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[s1973/hackintosh-hasee-k650d-i7-d3] 怎么启用屏幕亮度控制呢？ (#1)




那个地址好像打不开，我这个库里有直接编译好的SSDT-PNLF.aml，下载下来即可

**Comment by Hsiao-Jan** [comment]
> 那个地址好像打不开，我这个库里有直接编译好的[_SSDT-PNLF.aml_](https://github.com/s1973/hackintosh-hasee-k650d-i7-d3/blob/master/CLOVER/ACPI/patched/SSDT-PNLF.aml)，[下载](https://github.com/s1973/hackintosh-hasee-k650d-i7-d3/raw/master/CLOVER/ACPI/patched/SSDT-PNLF.aml)下来即可

我看了一下你给我贴的地址，我目前用的clover就是你这个啦，所以里面的SSDT-PNLF.aml就是你刚刚给我发的那个地址，我的k650d现在用fn+亮度控制键没有反应，但是亮度是可以在系统偏好设置里面调的，我想知道如何才能用快捷键。

**Comment by s1973** [comment]
使用[Karabiner](https://pqrs.org/osx/karabiner/)软件更改按键映射

**Comment by Hsiao-Jan** [comment]
好的 谢谢你啦  我暂时就先用这个软件吧 我把问题关了 麻烦你了 十分感谢
